// src/lib/editor/idiomaEditor.js
export const idiomaEditor = {
  es: {
    'editor.title': 'Dashboard de Redacción',
    'editor.nuevaHistoria': 'Nueva Historia',
    'editor.panelGestor': 'Panel Gestor',
    'editor.administrador': 'Administrador',
    'editor.gestorEditorial': 'Gestor Editorial',
    'editor.editorWorkwii': 'Editor de Workwii',
    'editor.misHistorias': 'Mis Historias',
    'editor.publicas': 'Públicas',
    'editor.borradores': 'Borradores',
    'editor.fijados': 'Fijados (Pins)',
    'editor.administrarContenido': 'Administrar Contenido',
    'editor.articulosEncontrados': '{count} artículos encontrados',
    'editor.articuloEncontrado': '{count} artículo encontrado',
    'editor.buscarTitulo': 'Buscar por título...',
    'editor.todos': 'Todos',
    'editor.publicos': 'Públicos',
    'editor.idioma': 'Idioma:',
    'editor.articulo': 'Artículo',
    'editor.categoria': 'Categoría',
    'editor.estado': 'Estado',
    'editor.publicado': 'Publicado',
    'editor.acciones': 'Acciones',
    'editor.cargandoEspacio': 'Cargando tu espacio de trabajo...',
    'editor.sinResultados': 'Sin resultados',
    'editor.primerPost': 'Aún no has redactado ninguna historia en Workwii. ¡Crea tu primer post!',
    'editor.coincidencia': 'Ninguna de tus historias coincide con la búsqueda.',
    'editor.cargando': 'Cargando...',
    'editor.eliminarArticulo': '¿Eliminar artículo?',
    'editor.confirmarBorrado': '¿Estás seguro de que deseas eliminar la historia {title}? <br /><br />Esta acción es permanente y no se podrá deshacer. El artículo será retirado inmediatamente del blog público de Workwii.',
    'editor.cancelar': 'Cancelar',
    'editor.siEliminar': 'Sí, Eliminar',
    'editor.general': 'General',
    'editor.publico': 'Público',
    'editor.borrador': 'Borrador',
    'editor.pin': 'Pin',
    'editor.eliminado': 'Artículo eliminado permanentemente',
    'editor.errorEliminar': 'Error al intentar eliminar el artículo',
    'editor.errorCarga': 'Error cargando base de datos'
  },
  en: {
    'editor.title': 'Writing Dashboard',
    'editor.nuevaHistoria': 'New Story',
    'editor.panelGestor': 'Editor Panel',
    'editor.administrador': 'Administrator',
    'editor.gestorEditorial': 'Editorial Manager',
    'editor.editorWorkwii': 'Workwii Writer',
    'editor.misHistorias': 'My Stories',
    'editor.publicas': 'Public',
    'editor.borradores': 'Drafts',
    'editor.fijados': 'Pinned (Pins)',
    'editor.administrarContenido': 'Manage Content',
    'editor.articulosEncontrados': '{count} articles found',
    'editor.articuloEncontrado': '{count} article found',
    'editor.buscarTitulo': 'Search by title...',
    'editor.todos': 'All',
    'editor.publicos': 'Public',
    'editor.idioma': 'Language:',
    'editor.articulo': 'Article',
    'editor.categoria': 'Category',
    'editor.estado': 'Status',
    'editor.publicado': 'Published',
    'editor.acciones': 'Actions',
    'editor.cargandoEspacio': 'Loading your workspace...',
    'editor.sinResultados': 'No results',
    'editor.primerPost': "You haven't written any stories on Workwii yet. Create your first post!",
    'editor.coincidencia': 'None of your stories match the search.',
    'editor.cargando': 'Loading...',
    'editor.eliminarArticulo': 'Delete article?',
    'editor.confirmarBorrado': 'Are you sure you want to delete the story {title}? <br /><br />This action is permanent and cannot be undone. The article will be immediately removed from Workwii public blog.',
    'editor.cancelar': 'Cancel',
    'editor.siEliminar': 'Yes, Delete',
    'editor.general': 'General',
    'editor.publico': 'Public',
    'editor.borrador': 'Draft',
    'editor.pin': 'Pin',
    'editor.eliminado': 'Article permanently deleted',
    'editor.errorEliminar': 'Error attempting to delete article',
    'editor.errorCarga': 'Error loading database'
  }
};
