// src/lib/usuarios/smile/idiomaSmile.js
export const idiomaSmile = {
  es: {
    'smile.title': 'Dashboard del Candidato',
    'smile.plan': 'Plan:',
    'smile.misHerramientas': 'Mis Herramientas de Éxito',
    'smile.misHerramientasDesc': 'Todo lo que necesitas para conseguir tu próximo gran empleo',
    'smile.crearCv': 'Crear Currículum ATS',
    'smile.crearCvDesc': 'Escribe tu información paso a paso mediante nuestro formulario clásico inteligente y optimizado.',
    'smile.analisarCv': 'Analizar CV con IA',
    'smile.analisarCvDesc': 'Sube o pega tu CV para medir tu puntuación ATS actual y recibir sugerencias críticas para mejorar.',
    'smile.postulaciones': 'Postulaciones y Empleo',
    'smile.irKanban': 'Ir al Kanban',
    'smile.postulado': 'Postulado',
    'smile.entrevista': 'Entrevista',
    'smile.oferta': 'Oferta',
    'smile.rechazado': 'Rechazado',
    'smile.plantillasFav': 'Plantillas Favoritas',
    'smile.plantillasDesc': 'Diseños aprobados por reclutadores',
    'smile.clasica': 'Clásica Profesional',
    'smile.moderna': 'Moderna Elegante',
    'smile.minimalista': 'Minimalista Limpia',
    'smile.popular': 'Popular',
    'smile.recomendada': 'Recomendada',
    'smile.nueva': 'Nueva',
    'smile.actividadReciente': 'Actividad Reciente',
    'smile.actividadDesc': 'Historial de tus acciones',
    'smile.actividadRegistro': 'Te registraste en {app}. ¡Bienvenido!',
    'smile.actividadListo': 'Tu currículum está listo para ser creado.',
    'smile.recienRegistrado': 'Recién registrado',
    'smile.pendiente': 'Pendiente',
  },
  en: {
    'smile.title': 'Candidate Dashboard',
    'smile.plan': 'Plan:',
    'smile.misHerramientas': 'My Success Tools',
    'smile.misHerramientasDesc': 'Everything you need to land your next great job',
    'smile.crearCv': 'Create ATS Resume',
    'smile.crearCvDesc': 'Write your info step by step using our classic smart and optimized form.',
    'smile.analisarCv': 'Analyze CV with AI',
    'smile.analisarCvDesc': 'Upload or paste your CV to measure your current ATS score and get critical suggestions to improve.',
    'smile.postulaciones': 'Applications & Jobs',
    'smile.irKanban': 'Go to Kanban',
    'smile.postulado': 'Applied',
    'smile.entrevista': 'Interview',
    'smile.oferta': 'Offer',
    'smile.rechazado': 'Rejected',
    'smile.plantillasFav': 'Favorite Templates',
    'smile.plantillasDesc': 'Recruiter-approved designs',
    'smile.clasica': 'Classic Professional',
    'smile.moderna': 'Modern Elegant',
    'smile.minimalista': 'Minimalist Clean',
    'smile.popular': 'Popular',
    'smile.recomendada': 'Recommended',
    'smile.nueva': 'New',
    'smile.actividadReciente': 'Recent Activity',
    'smile.actividadDesc': 'History of your actions',
    'smile.actividadRegistro': 'You registered on {app}. Welcome!',
    'smile.actividadListo': 'Your resume is ready to be created.',
    'smile.recienRegistrado': 'Just registered',
    'smile.pendiente': 'Pending',
  }
};
