export const idiomaAcerca = {
  es: {
    seo: {
      titulo: 'Acerca de nosotros - Workwii',
      descripcion: 'Conoce el propósito de Workwii, tu aliado inteligente con Inteligencia Artificial para potenciar tu CV y triunfar en tus procesos de selección.'
    },
    hero: {
      badge: 'Tu aliado inteligente para conseguir empleo',
      tit1: 'Workwii',
      sub: 'Optimiza tu currículum, supera los filtros ATS y simula entrevistas reales impulsadas por Inteligencia Artificial para destacar en el mercado laboral.',
      stat1_num: '100%',
      stat1_lbl: 'Optimización ATS',
      stat2_num: 'Gratis',
      stat2_lbl: 'Completamente gratis',
      stat3_num: '24/7',
      stat3_lbl: 'Feedback con IA',
      stat4_num: '10K+',
      stat4_lbl: 'CVs Mejorados',
      btnOptimizar: 'Optimizar CV',
      btnCompartir: 'Compartir App',
      btnCompartido: '¡Link copiado!'
    },
    counters: {
      c1_num: '100',
      c1_lbl: 'Gratis para siempre',
      c2_num: '99',
      c2_lbl: 'Velocidad de Carga',
      c3_lbl: 'Simulaciones IA',
      c4_num: '2026',
      c4_lbl: 'Siempre actualizado'
    },
    historia: {
      badge: 'Acerca de nosotros',
      tit: 'El propósito de ',
      p1: '<strong>Workwii</strong> es una aplicación diseñada para ayudarte a crear y optimizar tu currículum profesional. Su propósito es ayudarte a superar los exigentes filtros ATS (Applicant Tracking Systems) y prepararte adecuadamente para tus futuras entrevistas laborales.',
      p2: 'Inspirados en la necesidad de democratizar el acceso a herramientas profesionales de calidad, desarrollamos una plataforma que actúa como el puente inteligente entre tu perfil actual y tu próximo gran empleo. Creemos firmemente que la preparación técnica y el feedback oportuno marcan la diferencia en los procesos de selección modernos.',
      p3: 'Además de un lienzo interactivo para redactar tus documentos de forma limpia y organizada en tiempo real, integramos un sistema de asistencia por IA capaz de simular entrevistas reales. Podrás entrenar tus respuestas en base al puesto al que postulas, recibiendo retroalimentación constructiva al instante.',
      p4: 'Esta app fue construida para digitalizar estos recursos y hacerlos 100% accesibles para todos los profesionales en búsqueda de nuevas oportunidades, en cualquier momento y desde cualquier dispositivo.',
      p5: 'Agradecemos sinceramente tu confianza en nosotros. ¡Te deseamos el mayor de los éxitos en tu camino profesional y recuerda que tu potencial no tiene límites!',
      firmaNombre: 'Con aprecio, Wilder Taype',
      firmaRol: 'Creador de Workwii'
    },
    beneficios: {
      badge: '¿Por qué Workwii?',
      tit: 'Beneficios para impulsar tu ',
      titGrad: 'perfil laboral',
      sub: 'Herramientas profesionales potenciadas por Inteligencia Artificial',
      b1_tit: 'Editor de CV Profesional',
      b1_desc: 'Crea y edita tus documentos profesionales en tiempo real con un lienzo optimizado y libre de distracciones.',
      b2_tit: 'Optimización ATS',
      b2_desc: 'Analiza y adapta tu CV según las palabras clave requeridas por las empresas para superar filtros automatizados.',
      b3_tit: 'Simulador de Entrevistas',
      b3_desc: 'Practica con una IA entrenada que te hará preguntas reales de reclutamiento según tu especialidad y puesto objetivo.',
      b4_tit: 'Consejos de Empleo',
      b4_desc: 'Accede a guías y plantillas detalladas para optimizar tu redacción, mejorar tu marca personal y captar reclutadores.',
      b5_tit: 'Interfaz Premium',
      b5_desc: 'Cada animación y detalle visual está adaptado con colores suaves para brindarte una zona de trabajo cómoda y veloz.',
      b6_tit: '100% Responsivo',
      b6_desc: 'Lleva tu currículum contigo. Edita, estructura y consulta tus notas de empleo cómodamente desde cualquier dispositivo móvil.'
    },
    pasos: {
      badge: 'Empieza ahora',
      tit: '3 pasos para ',
      titGrad: 'destacar',
      sub: 'Optimiza tu perfil profesional en minutos',
      p1_tit: 'Redacta',
      p1_desc: 'Escribe y estructura el contenido de tu currículum profesional en nuestro editor dinámico.',
      p2_tit: 'Optimiza',
      p2_desc: 'Ajusta el vocabulario técnico para superar las pruebas de los filtros automáticos ATS.',
      p3_tit: 'Simula',
      p3_desc: 'Responde preguntas de IA de reclutamiento real y entrena tus respuestas para triunfar.'
    },
    testimonios: {
      badge: 'Comunidad',
      tit: 'Profesionales que usan ',
      sub: 'Casos de éxito y testimonios de nuestra comunidad laboral',
      t1_txt: '"El editor en tiempo real y los consejos de IA me ayudaron a estructurar mi CV en minutos. Conseguí mi primera entrevista técnica en semanas."',
      t1_aut: 'María C.',
      t1_crg: 'Ingeniera de Software',
      t2_txt: '"Simular la entrevista técnica con la IA me dio la confianza que necesitaba. El feedback de las preguntas fue muy acertado y directo."',
      t2_aut: 'Juan Pérez',
      t2_crg: 'Analista de Datos',
      t3_txt: '"Me encantan los consejos del blog con plantillas. La interfaz oscura es preciosa y me permite trabajar de noche sin cansar la vista."',
      t3_aut: 'Rosa M.',
      t3_crg: 'Administradora',
      t4_txt: '"Superar los filtros automáticos (ATS) siempre fue mi dolor de cabeza. Gracias al analizador de palabras clave logré pasar el primer filtro."',
      t4_aut: 'Carlos G.',
      t4_crg: 'Project Manager',
      t5_txt: '"La rapidez de la aplicación móvil es fantástica. Puedo revisar y actualizar mis notas profesionales de camino a las oficinas de selección."',
      t5_aut: 'Elena R.',
      t5_crg: 'Consultora de RRHH',
      t6_txt: '"Workwii se ha convertido en mi herramienta diaria de desarrollo profesional. Las guías de CV son oro puro para cualquier postulante."',
      t6_aut: 'Pedro S.',
      t6_crg: 'Diseñador UX'
    },
    funciones: {
      badge: 'Funciones',
      tit: 'Herramientas para ',
      titGrad: 'potenciar tu perfil',
      sub: 'Diseñadas para acompañarte en tu preparación profesional y laboral',
      f1_tit: 'Editor de CV',
      f1_sub: 'Escribe tu currículum',
      f2_tit: 'Entrevista IA',
      f2_sub: 'Simula preguntas reales'
    },
    cta: {
      tit: '¿Listo para dar el<br>siguiente paso?',
      sub: 'Optimiza tu perfil profesional y supera cualquier proceso de selección hoy mismo.',
      chipEditor: 'Editor de CV',
      chipSimulador: 'Simulador IA',
      btnEditor: 'Ir al Editor',
      btnBlog: 'Ver Blog'
    },
    shareText: 'Optimiza tu CV y supera entrevistas con la ayuda de la Inteligencia Artificial.'
  },
  en: {
    seo: {
      titulo: 'About Us - Workwii',
      descripcion: 'Learn about the purpose of Workwii, your AI-powered smart ally to optimize your resume and succeed in your job recruitment processes.'
    },
    hero: {
      badge: 'Your smart partner to get a job',
      tit1: 'Workwii',
      sub: 'Optimize your resume, beat ATS filters, and practice real AI-powered interview simulations to stand out in the job market.',
      stat1_num: '100%',
      stat1_lbl: 'ATS Optimization',
      stat2_num: 'Free',
      stat2_lbl: 'Completely free',
      stat3_num: '24/7',
      stat3_lbl: 'AI Feedback',
      stat4_num: '10K+',
      stat4_lbl: 'Resumes Improved',
      btnOptimizar: 'Optimize CV',
      btnCompartir: 'Share App',
      btnCompartido: 'Link copied!'
    },
    counters: {
      c1_num: '100',
      c1_lbl: 'Free forever',
      c2_num: '99',
      c2_lbl: 'Loading Speed',
      c3_lbl: 'AI Simulations',
      c4_num: '2026',
      c4_lbl: 'Always updated'
    },
    historia: {
      badge: 'About us',
      tit: 'The purpose of ',
      p1: '<strong>Workwii</strong> is an application designed to help you build and optimize your professional resume. Its purpose is to help you pass demanding ATS (Applicant Tracking Systems) filters and adequately prepare for your future job interviews.',
      p2: 'Inspired by the need to democratize access to quality professional tools, we developed a platform that acts as the smart bridge between your current profile and your next great job. We firmly believe that technical preparation and timely feedback make a difference in modern recruitment processes.',
      p3: 'In addition to an interactive canvas to draft your documents cleanly and organized in real-time, we integrated an AI-based assistance system capable of simulating real interviews. You will be able to practice your answers based on the position you are applying for, receiving constructive feedback instantly.',
      p4: 'This app was built to digitize these resources and make them 100% accessible to all professionals searching for new opportunities, at any time and from any device.',
      p5: 'We sincerely appreciate your trust in us. We wish you the greatest success in your career path and remember that your potential has no limits!',
      firmaNombre: 'With appreciation, Wilder Taype',
      firmaRol: 'Creator of Workwii'
    },
    beneficios: {
      badge: 'Why Workwii?',
      tit: 'Benefits to boost your ',
      titGrad: 'career profile',
      sub: 'AI-powered professional tools for your success',
      b1_tit: 'Professional CV Editor',
      b1_desc: 'Create and edit your professional documents in real time with a distraction-free, optimized canvas.',
      b2_tit: 'ATS Optimization',
      b2_desc: 'Analyze and adapt your CV according to the keywords required by companies to pass automated filters.',
      b3_tit: 'Interview Simulator',
      b3_desc: 'Practice with a trained AI that will ask you real recruitment questions based on your specialty and target job.',
      b4_tit: 'Career Advice',
      b4_desc: 'Access detailed guides and templates to optimize your writing, improve your personal brand, and catch recruiters.',
      b5_tit: 'Premium Interface',
      b5_desc: 'Every animation and visual detail is tailored with soft colors to provide you with a comfortable and fast workspace.',
      b6_tit: '100% Responsive',
      b6_desc: 'Take your resume with you. Edit, structure, and check your job notes comfortably from any mobile device.'
    },
    pasos: {
      badge: 'Get started now',
      tit: '3 steps to ',
      titGrad: 'stand out',
      sub: 'Optimize your professional profile in minutes',
      p1_tit: 'Draft',
      p1_desc: 'Write and structure the content of your professional resume in our dynamic editor.',
      p2_tit: 'Optimize',
      p2_desc: 'Adjust technical vocabulary to pass automated ATS filter checks.',
      p3_tit: 'Simulate',
      p3_desc: 'Answer real AI recruitment questions and train your responses to succeed.'
    },
    testimonios: {
      badge: 'Community',
      tit: 'Professionals using ',
      sub: 'Success stories and testimonials from our professional community',
      t1_txt: '"The real-time editor and AI tips helped me structure my resume in minutes. I got my first technical interview in weeks."',
      t1_aut: 'Maria C.',
      t1_crg: 'Software Engineer',
      t2_txt: '"Simulating the technical interview with AI gave me the confidence I needed. The feedback on questions was spot on and direct."',
      t2_aut: 'John Doe',
      t2_crg: 'Data Analyst',
      t3_txt: '"I love the blog posts with templates. The dark interface is gorgeous and lets me work at night without tiring my eyes."',
      t3_aut: 'Rosa M.',
      t3_crg: 'Administrator',
      t4_txt: '"Passing automatic filters (ATS) was always my headache. Thanks to the keyword analyzer, I managed to pass the first filter."',
      t4_aut: 'Charles G.',
      t4_crg: 'Project Manager',
      t5_txt: '"The speed of the mobile app is fantastic. I can review and update my career notes on my way to recruitment offices."',
      t5_aut: 'Helen R.',
      t5_crg: 'HR Consultant',
      t6_txt: '"Workwii has become my daily professional development tool. The CV guides are pure gold for any applicant."',
      t6_aut: 'Peter S.',
      t6_crg: 'UX Designer'
    },
    funciones: {
      badge: 'Features',
      tit: 'Tools to ',
      titGrad: 'boost your profile',
      sub: 'Designed to accompany you in your professional and career preparation',
      f1_tit: 'CV Editor',
      f1_sub: 'Write your resume',
      f2_tit: 'AI Interview',
      f2_sub: 'Simulate real questions'
    },
    cta: {
      tit: 'Ready to take the<br>next step?',
      sub: 'Optimize your professional profile and pass any selection process today.',
      chipEditor: 'CV Editor',
      chipSimulador: 'AI Simulator',
      btnEditor: 'Go to Editor',
      btnBlog: 'View Blog'
    },
    shareText: 'Optimize your resume and pass interviews with the help of Artificial Intelligence.'
  }
};
