// src/lib/crear/idiomaCrear.js
// Diccionario descentralizado de traducciones para el Creador de CV y Consejos (Astro-way)

export const idiomaCrear = {
  es: {
    'crear.titulo': 'Creador de CV',
    'crear.subtitulo': 'ATS Profesional',
    'crear.desc': 'Escribe y optimiza tu CV con inteligencia artificial para superar los algoritmos de selección.',
    'crear.subirBtn': 'Subir CV existente (Opcional)',
    'crear.subirBtnHelp': '¿Tienes un CV antiguo? Súbelo en PDF o Word y rellenaremos los campos automáticamente. ¡Es opcional, pero te ahorrará mucho tiempo!',
    'crear.nuevoBtn': 'Crear nuevo CV',
    'crear.nuevoBtnHelp': 'Esto borrará todo tu progreso actual en tu navegador para que puedas crear un currículum nuevo desde cero.',
    'crear.descargarBtn': 'Descargar CV',
    'crear.descargarBtnHelp': 'Descarga directa de tu currículum en formato PDF optimizado para ATS.',
    'crear.printBtn': 'Imprimir PDF (Recomendado ATS)',
    'crear.dwPdfBtn': 'Descargar PDF (Exportación Directa)',
    'crear.dwDocxBtn': 'Descargar Word (.docx)',
    'crear.dwTxtBtn': 'Descargar Texto (.txt)',
    'crear.dwMdBtn': 'Descargar Markdown (.md)',
    'crear.dwJsonBtn': 'Respaldar datos (.json)',
    'crear.compatibilidad': 'Compatibilidad ATS:',
    'crear.optimizarBtn': 'Optimizar con Botwii',
    'crear.optimizarBtnHelp': 'Haz clic para que Botwii optimice automáticamente todo tu currículum: reescribirá tus logros con verbos fuertes, pulirá tu resumen e integrará mejoras ATS clave.',
    'crear.scoreHelp': 'Tu porcentaje de compatibilidad ATS actual. Mientras más alto, más probabilidades tendrás de superar los filtros automáticos.',
    'crear.templateHelp': 'Esta es una plantilla ATS clásica limpia. Los reclutadores prefieren este formato sobrio porque los robots de IA pueden leerlo sin errores.',
    
    // Modal de optimización de logros
    'crear.modalIaTitulo': 'Optimizar Logro con IA',
    'crear.modalIaDesc': 'La inteligencia artificial de Gemini reescribirá tu experiencia aplicando reglas de impacto ATS (verbos de acción fuertes y enfoque a resultados).',
    'crear.modalIaOriginal': 'Tu redacción original:',
    'crear.modalIaSugerencia': 'Sugerencia de Gemini ✨:',
    'crear.modalIaCargando': 'Optimizando tu redacción, por favor espera...',
    'crear.modalIaDescartar': 'Descartar',
    'crear.modalIaAplicar': 'Aplicar Cambios',
    
    // Modal de confirmación de reset
    'crear.modalResetTitulo': '¿Crear nuevo currículum?',
    'crear.modalResetDesc': 'Esto borrará de forma permanente todo tu progreso actual en este navegador. ¿Estás seguro de que deseas empezar de cero?',
    'crear.modalResetConfirmar': 'Sí, crear nuevo',
    'crear.modalResetCancelar': 'Cancelar',

    // Consejos.astro
    'crear.consejos.badge': 'Guía Científica',
    'crear.consejos.titulo': 'Buenas Prácticas para un ',
    'crear.consejos.tituloSpan': 'CV ATS Flawless',
    'crear.consejos.desc': 'Alinea tu currículum con los estándares de lectura automática recomendados por los departamentos de reclutamiento líderes del sector tecnológico.',
    'crear.consejos.categoria': 'Categoría',
    'crear.consejos.recomendada': 'Práctica Recomendada',
    'crear.consejos.evitar': 'Práctica a Evitar',
    'crear.consejos.catTipografia': 'Tipografía',
    'crear.consejos.recTipografia': 'Fuentes estándar legibles como Roboto, Arial o Helvetica (10pt a 11pt) con negrita clara en tu nombre, cargos y empresas.',
    'crear.consejos.evitTipografia': 'Fuentes cursivas, decorativas o tipografías no estándar. Evitar tamaños demasiado reducidos (menores a 9.5pt).',
    'crear.consejos.catAlineacion': 'Alineación',
    'crear.consejos.recAlineacion': 'Alineación estricta a la izquierda para el perfil profesional y logros, garantizando una lectura lineal natural del parser.',
    'crear.consejos.evitAlineacion': 'Texto justificado. Los espacios desiguales entre palabras pueden fragmentar frases clave y confundir al robot.',
    'crear.consejos.catEstructura': 'Estructura',
    'crear.consejos.recEstructura': 'Diseño de flujo continuo de una sola columna o columnas de texto vectoriales nativas para ordenar la cronología.',
    'crear.consejos.evitEstructura': 'Tablas HTML (<table>) o cuadros de texto flotantes. El texto dentro de ellos se extrae fuera de orden o se mezcla.',
    'crear.consejos.catVisuales': 'Elementos Visuales',
    'crear.consejos.recVisuales': 'Viñetas estándar y limpias (- o •) para listar tus funciones. Enfocarse al 100% en texto legible.',
    'crear.consejos.evitVisuales': 'Fotos, logotipos de empresas, gráficos de barras para medir habilidades o iconos complejos en el texto.',
    'crear.consejos.catDimensiones': 'Dimensiones',
    'crear.consejos.recDimensiones': 'Márgenes uniformes y consistentes de entre 0.5 y 1 pulgada. Exportación a tamaño de página A4 o Letter estándar.',
    'crear.consejos.evitDimensiones': 'Márgenes desiguales o extremadamente reducidos para forzar texto, lo que arruina la impresión física.',
    'crear.consejos.citasTitulo': 'Citas de Autoridad y Respaldo',
    'crear.consejos.harvardTexto': '"Un formato simple de una sola columna, sin tablas ni imágenes decorativas, incrementa hasta en un 60% la probabilidad de que un parser ATS indexe el currículum de forma correcta."',
    'crear.consejos.harvardAutor': 'Guía oficial de reclutamiento corporativo',
    'crear.consejos.mitTexto': '"El uso de negrita clara en cargos y nombres de empresa clave reduce el tiempo de revisión humana (promedio de 6 segundos) y duplica la tasa de retención visual del reclutador."',
    'crear.consejos.mitAutor': 'Estudio de empleabilidad y ergonomía visual',
    'crear.consejos.googleTexto': '"Los algoritmos ATS ignoran de forma sistemática el texto ubicado dentro de encabezados, pies de página o cuadros de texto separados, resultando en descartes prematuros."',
    'crear.consejos.googleAutor': 'Recomendaciones oficiales para procesos de ingeniería'
  },
  en: {
    'crear.titulo': 'CV Builder',
    'crear.subtitulo': 'ATS Professional',
    'crear.desc': 'Write and optimize your resume with artificial intelligence to beat the selection algorithms.',
    'crear.subirBtn': 'Upload existing CV (Optional)',
    'crear.subirBtnHelp': 'Do you have an old CV? Upload it in PDF or Word and we will fill in the fields automatically. It is optional, but it will save you a lot of time!',
    'crear.nuevoBtn': 'Create new CV',
    'crear.nuevoBtnHelp': 'This will erase all your current progress in your browser so you can start a new resume from scratch.',
    'crear.descargarBtn': 'Download CV',
    'crear.descargarBtnHelp': 'Direct download of your resume in ATS-optimized PDF format.',
    'crear.printBtn': 'Print PDF (ATS Recommended)',
    'crear.dwPdfBtn': 'Download PDF (Direct Export)',
    'crear.dwDocxBtn': 'Download Word (.docx)',
    'crear.dwTxtBtn': 'Download Text (.txt)',
    'crear.dwMdBtn': 'Download Markdown (.md)',
    'crear.dwJsonBtn': 'Backup data (.json)',
    'crear.compatibilidad': 'ATS Compatibility:',
    'crear.optimizarBtn': 'Optimize with Botwii',
    'crear.optimizarBtnHelp': 'Click to have Botwii automatically optimize your entire resume: it will rewrite your achievements with strong action verbs, polish your summary, and integrate key ATS improvements.',
    'crear.scoreHelp': 'Your current ATS compatibility percentage. The higher it is, the more likely you are to pass automatic filters.',
    'crear.templateHelp': 'This is a clean classic ATS template. Recruiters prefer this sober format because AI bots can read it without errors.',
    
    // Achievement optimization modal
    'crear.modalIaTitulo': 'Optimize Achievement with AI',
    'crear.modalIaDesc': "Gemini's artificial intelligence will rewrite your experience applying ATS impact rules (strong action verbs and results-oriented focus).",
    'crear.modalIaOriginal': 'Your original wording:',
    'crear.modalIaSugerencia': "Gemini's Suggestion ✨:",
    'crear.modalIaCargando': 'Optimizing your writing, please wait...',
    'crear.modalIaDescartar': 'Discard',
    'crear.modalIaAplicar': 'Apply Changes',
    
    // Reset confirmation modal
    'crear.modalResetTitulo': 'Create new resume?',
    'crear.modalResetDesc': 'This will permanently delete all your current progress in this browser. Are you sure you want to start from scratch?',
    'crear.modalResetConfirmar': 'Yes, create new',
    'crear.modalResetCancelar': 'Cancel',

    // Consejos.astro
    'crear.consejos.badge': 'Scientific Guide',
    'crear.consejos.titulo': 'Best Practices for a ',
    'crear.consejos.tituloSpan': 'Flawless ATS CV',
    'crear.consejos.desc': 'Align your resume with the automatic reading standards recommended by leading recruitment departments in the tech sector.',
    'crear.consejos.categoria': 'Category',
    'crear.consejos.recomendada': 'Recommended Practice',
    'crear.consejos.evitar': 'Practice to Avoid',
    'crear.consejos.catTipografia': 'Typography',
    'crear.consejos.recTipografia': 'Standard legible fonts like Roboto, Arial, or Helvetica (10pt to 11pt) with clear bolding on your name, job titles, and companies.',
    'crear.consejos.evitTipografia': 'Italic, decorative, or non-standard fonts. Avoid excessively small sizes (under 9.5pt).',
    'crear.consejos.catAlineacion': 'Alignment',
    'crear.consejos.recAlineacion': 'Strict left-alignment for the professional summary and achievements, guaranteeing natural linear parsing.',
    'crear.consejos.evitAlineacion': 'Justified text. Uneven spaces between words can fragment key phrases and confuse the robot.',
    'crear.consejos.catEstructura': 'Structure',
    'crear.consejos.recEstructura': 'Single-column continuous flow layout or native vector text columns to order the chronology.',
    'crear.consejos.evitEstructura': 'HTML tables (<table>) or floating text boxes. Text inside them is extracted out of order or mixed.',
    'crear.consejos.catVisuales': 'Visual Elements',
    'crear.consejos.recVisuales': 'Standard clean bullets (- or •) to list your roles. Focus 100% on legible text.',
    'crear.consejos.evitVisuales': 'Photos, company logos, bar charts to measure skills, or complex icons in text.',
    'crear.consejos.catDimensiones': 'Dimensions',
    'crear.consejos.recDimensiones': 'Uniform, consistent margins between 0.5 and 1 inch. Export to standard A4 or Letter page size.',
    'crear.consejos.evitDimensiones': 'Uneven or extremely small margins to force text, which ruins physical printing.',
    'crear.consejos.citasTitulo': 'Authority Quotes & Backing',
    'crear.consejos.harvardTexto': '"A simple single-column format, without tables or decorative images, increases the probability of an ATS parser indexing the resume correctly by up to 60%."',
    'crear.consejos.harvardAutor': 'Official corporate recruitment guide',
    'crear.consejos.mitTexto': '"The use of clear bolding on key job titles and company names reduces human review time (average of 6 seconds) and doubles the recruiter\'s visual retention rate."',
    'crear.consejos.mitAutor': 'Study of employability and visual ergonomics',
    'crear.consejos.googleTexto': '"ATS algorithms systematically ignore text located inside headers, footers, or separate text boxes, resulting in premature rejections."',
    'crear.consejos.googleAutor': 'Official recommendations for engineering processes'
  }
};
