// src/lib/todos/blog/nuevo/idiomaNuevo.js
// Traducciones para el panel del creador/editor de blog

export const idiomaNuevo = {
  es: {
    'nuevo.title': 'Creador de Artículos — Admin',
    'nuevo.nuevaPublicacion': 'Nueva publicación',
    'nuevo.editarPublicacion': 'Editar publicación',
    'nuevo.editando': 'Editando:',
    'nuevo.verPost': 'Ver post',
    'nuevo.sincronizarBorrador': 'Sincronizar borrador local',
    'nuevo.publicar': 'Publicar',
    'nuevo.guardar': 'Guardar',
    'nuevo.guardarCambios': 'Guardar cambios',
    'nuevo.actualizar': 'Actualizar',
    'nuevo.titulo': 'Título',
    'nuevo.escribeTitulo': 'Escribe un título impactante... (Mínimo: 35, Mínimo: 47)',
    'nuevo.resumenLectura': 'Resumen de lectura',
    'nuevo.escribeResumen': 'Escribe una descripción breve que enganche... (Mínimo: 100, Máximo: 200)',
    'nuevo.keywords': 'Palabras clave (SEO Keywords)',
    'nuevo.escribeKeywords': 'Escribe keywords separadas por comas... (Ej: empleo, ats, curriculum)',
    'nuevo.redactorContenido': 'Redactor de Contenido',
    'nuevo.contenido': 'Contenido',
    'nuevo.vistaPrevia': 'Vista previa',
    'nuevo.escribeContenido': 'Escribe el contenido de tu artículo usando formato Markdown...',
    'nuevo.palabras': '{count} palabras',
    'nuevo.lectura': '{count} min',
    'nuevo.activoLabel': 'Publicar inmediatamente',
    'nuevo.pinLabel': 'Destacar artículo (Pin)',
    'nuevo.cargandoAutor': 'Cargando...',
    'nuevo.categoria': 'Categoría',
    'nuevo.escribeCategoria': 'Escribe una categoría',
    'nuevo.tags': 'Tags',
    'nuevo.escribeTags': 'Escribe tags con comas',
    'nuevo.imagenes': 'Imágenes',
    'nuevo.miniatura': 'Miniatura (Inicio-Blog)',
    'nuevo.cabecera': 'Cabecera (Imagen Principal)',
    'nuevo.quitar': 'Quitar',
    'nuevo.slugBloqueado': 'Slug bloqueado (edición)',
    'nuevo.muyCorto': 'Muy corto',
    'nuevo.valido': 'Válido',
    'nuevo.excelente': 'Excelente',
    'nuevo.yaExiste': 'Ya existe',
    'nuevo.ok': 'OK',
    'nuevo.validando': 'Validando...',
    'nuevo.escribeTituloYContenido': 'Escribe un título y contenido antes de traducir',
    'nuevo.escribeTituloYContenidoClonar': 'Escribe un título y contenido antes de clonar',
    'nuevo.clonandoYTraduciendo': 'Traduciendo...',
    'nuevo.clonarExito': '¡Traducción completada con éxito como borrador de nuevo post!',
    'nuevo.clonarError': 'Error al clonar y traducir',
    'nuevo.sincronizadoExito': '¡Artículo sincronizado con éxito!',
    'nuevo.sincronizadoError': 'No se pudo conectar con cargar.js',
    'nuevo.errorCargarPost': 'Error cargando post',
    'nuevo.postActualizado': '¡Publicación actualizada!',
    'nuevo.postCreado': '¡Publicación creada con éxito!',
    'nuevo.errorGuardar': 'Error al guardar',
    'nuevo.errorPublicar': 'Error al publicar',
    
    // Originales de la traducción
    language: 'Idioma del artículo',
    originalPost: 'Vincular con post original (Traducción)',
    selectPost: '-- Ninguno (Post original) --',
    translateAi: 'Traducir con IA',
    translating: 'Traduciendo...',
    translateSuccess: '¡Campos traducidos e inyectados! (Recuerda guardar)',
    translateError: 'Error al traducir con Gemini',
    es: 'Español',
    en: 'Inglés'
  },
  en: {
    'nuevo.title': 'Article Creator — Admin',
    'nuevo.nuevaPublicacion': 'New publication',
    'nuevo.editarPublicacion': 'Edit publication',
    'nuevo.editando': 'Editing:',
    'nuevo.verPost': 'View post',
    'nuevo.sincronizarBorrador': 'Sync local draft',
    'nuevo.publicar': 'Publish',
    'nuevo.guardar': 'Save',
    'nuevo.guardarCambios': 'Save changes',
    'nuevo.actualizar': 'Update',
    'nuevo.titulo': 'Title',
    'nuevo.escribeTitulo': 'Write a catchy title... (Min: 35, Max: 47)',
    'nuevo.resumenLectura': 'Reading summary',
    'nuevo.escribeResumen': 'Write a hook description... (Min: 100, Max: 200)',
    'nuevo.keywords': 'Keywords (SEO Keywords)',
    'nuevo.escribeKeywords': 'Enter comma-separated keywords... (E.g. jobs, ats, resume)',
    'nuevo.redactorContenido': 'Content Editor',
    'nuevo.contenido': 'Content',
    'nuevo.vistaPrevia': 'Preview',
    'nuevo.escribeContenido': 'Write your article content using Markdown format...',
    'nuevo.palabras': '{count} words',
    'nuevo.lectura': '{count} min',
    'nuevo.activoLabel': 'Publish immediately',
    'nuevo.pinLabel': 'Pin article',
    'nuevo.cargandoAutor': 'Loading...',
    'nuevo.categoria': 'Category',
    'nuevo.escribeCategoria': 'Enter a category',
    'nuevo.tags': 'Tags',
    'nuevo.escribeTags': 'Enter comma-separated tags',
    'nuevo.imagenes': 'Images',
    'nuevo.miniatura': 'Thumbnail (Home-Blog)',
    'nuevo.cabecera': 'Header (Main Image)',
    'nuevo.quitar': 'Remove',
    'nuevo.slugBloqueado': 'Slug locked (editing)',
    'nuevo.muyCorto': 'Too short',
    'nuevo.valido': 'Valid',
    'nuevo.excelente': 'Excellent',
    'nuevo.yaExiste': 'Already exists',
    'nuevo.ok': 'OK',
    'nuevo.validando': 'Validating...',
    'nuevo.escribeTituloYContenido': 'Write a title and content before translating',
    'nuevo.escribeTituloYContenidoClonar': 'Write a title and content before cloning',
    'nuevo.clonandoYTraduciendo': 'Translating...',
    'nuevo.clonarExito': 'Translation successfully completed as a new post draft!',
    'nuevo.clonarError': 'Error cloning and translating',
    'nuevo.sincronizadoExito': 'Article successfully synchronized!',
    'nuevo.sincronizadoError': 'Could not connect to cargar.js',
    'nuevo.errorCargarPost': 'Error loading post',
    'nuevo.postActualizado': 'Publication updated!',
    'nuevo.postCreado': 'Publication created successfully!',
    'nuevo.errorGuardar': 'Error saving',
    'nuevo.errorPublicar': 'Error publishing',

    // Originales de la traducción
    language: 'Article Language',
    originalPost: 'Link with original post (Translation)',
    selectPost: '-- None (Original post) --',
    translateAi: 'Translate with AI',
    translating: 'Translating...',
    translateSuccess: 'Fields translated and filled! (Remember to save)',
    translateError: 'Failed to translate with Gemini',
    es: 'Spanish',
    en: 'English'
  }
};
