export const idiomaTerminos = {
  es: {
    seo: {
      titulo: 'Términos y Condiciones - Workwii',
      description: 'Reglas, responsabilidades, propiedad intelectual y condiciones de uso bajo las cuales ofrecemos nuestras herramientas gratuitas de preparación laboral.'
    },
    hero: {
      badge: 'Transparencia y Compromiso',
      tit1: 'Términos y',
      titGrad: 'Condiciones',
      sub: 'Al usar Workwii, te unes a una comunidad profesional. Estos términos aseguran que nuestro espacio siga siendo <strong>seguro, confiable y protegido para todos.</strong>',
      chip1: 'Tu privacidad es sagrada',
      chip2: 'Contenido gratuito',
      chip3: 'Uso justo',
      lastUpd: 'Última actualización: Abril'
    },
    indices: [
      { id: 'tm_sec_0', ico: 'fa-user-shield', color: '#0EBEFF', txt: 'Uso de la Plataforma' },
      { id: 'tm_sec_1', ico: 'fa-cloud-bolt', color: '#29C72E', txt: 'Sincronización y Datos' },
      { id: 'tm_sec_2', ico: 'fa-bullhorn', color: '#FF5C69', txt: 'Publicidad y Cookies' },
      { id: 'tm_sec_3', ico: 'fa-copyright', color: '#7000FF', txt: 'Propiedad Intelectual' },
      { id: 'tm_sec_4', ico: 'fa-shield-heart', color: '#FFDA34', txt: 'Exclusión de Responsabilidad' },
      { id: 'tm_sec_5', ico: 'fa-ban', color: '#FF5C69', txt: 'Contenido Prohibido' },
      { id: 'tm_sec_6', ico: 'fa-gavel', color: '#0EBEFF', txt: 'Jurisdicción' },
      { id: 'tm_sec_7', ico: 'fa-rotate', color: '#29C72E', txt: 'Cambios' },
      { id: 'tm_sec_8', ico: 'fa-envelope', color: '#7000FF', txt: 'Contacto' }
    ],
    sections: {
      badge: 'Contenido',
      tit: 'Todo lo que necesitas ',
      titGrad: 'saber',
      sub: 'Lee con calma. Estamos aquí para ser transparentes contigo.',
      s1_tit: 'Uso de la Plataforma',
      s1_desc: 'Workwii es una plataforma digital dedicada a la optimización de CVs y simulación de entrevistas con IA. Ha sido construida con inmenso esfuerzo, dedicación y sacrificio personal para apoyar la empleabilidad de miles de profesionales. Al acceder, te comprometes a:',
      s1_item1: 'Respetar el trabajo del creador, la integridad del software y las reglas de uso.',
      s1_item2: 'No utilizar los flujos del asistente IA para spam, re-ingeniería o con fines de explotación comercial.',
      s1_item3: 'Mantener un trato respetuoso y constructivo dentro de la plataforma.',
      s1_item4: 'Ser mayor de 13 años para registrar una cuenta en la aplicación.',
      s1_item5: 'Aceptar que este servicio se ofrece de forma libre y gratuita, reservándonos el derecho de admisión de usuarios.',
      s2_tit: 'Sincronización, Red y Dispositivos',
      s2_desc: 'Utilizamos tecnologías avanzadas de almacenamiento local (LocalStorage) y base de datos (Supabase) para brindarte la mejor experiencia en tiempo real:',
      s2_item1: 'Tus borradores se almacenan localmente en tu navegador. Si limpias el historial o caché, los perderás a menos que hayas iniciado sesión.',
      s2_item2: 'El correcto guardado y sincronización depende directamente de tu estabilidad de red, conexión a internet y de tener un navegador moderno y actualizado.',
      s2_item3: 'No nos hacemos responsables por pérdidas de datos ocasionadas por fallos de red, caídas de energía o navegadores obsoletos.',
      s2_item4: 'La responsabilidad de realizar copias de seguridad del contenido de tu currículum recae exclusivamente en ti.',
      s3_tit: 'Publicidad, Cookies y Asistente Chatwii',
      s3_desc: 'Para financiar y mantener gratuito este ecosistema de alto rendimiento, utilizamos cookies y Google AdSense:',
      s3_item1: 'Para poder interactuar con **Chatwii (nuestro Asistente IA)**, es obligatorio e indispensable aceptar y permitir el uso de cookies y políticas de privacidad.',
      s3_item2: 'Si no deseas aceptar o permites bloquear las cookies, la funcionalidad del chat y la sincronización con IA quedarán deshabilitadas para proteger la integridad de los datos.',
      s3_item3: 'Google AdSense utiliza cookies (como NID/IDE) para personalizar anuncios basados en tus visitas previas. Puedes cambiarlas en <a href="https://adssettings.google.com" target="_blank" rel="noopener">Google Ads Settings</a>.',
      s3_item4: 'Queda estrictamente prohibido intentar burlar los bloqueos de cookies para usar el asistente IA.',
      s4_tit: 'Propiedad Intelectual y Blindaje de Código',
      s4_desc: 'Workwii es un proyecto original desarrollado por <strong>Wilder Taype</strong>. Todos los derechos reservados.',
      s4_item1: 'El código fuente, la maquetación visual (incluyendo el diseño del lienzo A4), los estilos CSS, las animaciones, los algoritmos de la IA y el motor Chatwii son propiedad exclusiva de su creador.',
      s4_item2: 'Queda prohibida toda copia, clonación, distribución o distribución comercial del diseño de interfaces y flujos interactivos de la plataforma sin autorización expresa por escrito.',
      s4_item3: 'El contenido escrito que ingresas en tu CV (datos de contacto, experiencia, estudios) es de tu propiedad exclusiva. Nosotros solo te damos el lienzo para estructurarlo.',
      s4_item4: 'Cualquier sugerencia de mejora enviada por feedback es de libre uso para el autor con el fin de optimizar el producto.',
      s5_tit: 'Limitación y Exclusión Absoluta de Responsabilidad',
      s5_desc: 'Workwii se proporciona "TAL CUAL" ("As-Is") sin garantías de ningún tipo. Debido a que el servicio se ofrece de manera gratuita, nuestra responsabilidad total está limitada a $0.00 USD:',
      s5_item1: 'No garantizamos la infalibilidad o disponibilidad ininterrumpida de las sugerencias del asistente IA.',
      s5_item2: 'No somos responsables, bajo ningún concepto, por decisiones o resultados en tus procesos de postulación, entrevistas fallidas o rechazos en filtros ATS de empresas.',
      s5_item3: 'Las alucinaciones, errores de redacción, gramática o sugerencias incorrectas que genere la IA deben ser validadas por el usuario. El usuario es el autor y editor final de su propio CV.',
      s5_item4: 'Nos reservamos el derecho de dar de baja el servicio, suspender cuentas o modificar herramientas en cualquier momento sin previo aviso.',
      s6_tit: 'Contenido y Actividades Prohibidas',
      s6_desc: 'Con el fin de mantener un ecosistema seguro para todos los candidatos, queda prohibido:',
      s6_item1: 'Subir información fraudulenta, títulos falsos o suplantar identidades en la plataforma.',
      s6_item2: 'Usar bots, scrapers o scripts automatizados para extraer información del blog o del editor.',
      s6_item3: 'Intentar hackear, inyectar código malicioso (SQL o XSS) o sabotear la base de datos de Supabase.',
      s6_item4: 'Copiar la identidad de marca o el material visual de Workwii para proyectos ajenos.',
      s6_item5: 'Realizar spam, phishing o fraude utilizando cualquiera de los canales y recursos de la web.',
      s7_tit: 'Jurisdicción y Ley Aplicable',
      s7_desc: 'Estos Términos se rigen bajo las leyes de la República del Perú. Toda disputa legal o reclamación judicial será resuelta de forma exclusiva en los fueros y tribunales de la ciudad de Lima, Perú.',
      s7_footer: 'Si alguna de las disposiciones es declarada nula o inaplicable por un tribunal, esto no afectará la validez y vigencia de las demás cláusulas aquí pactadas.',
      s8_tit: 'Cambios en las Condiciones',
      s8_desc: 'El creador se reserva el derecho de modificar o actualizar estos términos en cualquier momento para adaptarlos a nuevas regulaciones o funcionalidades de IA.',
      s8_footer: 'El uso continuado de las herramientas tras la actualización de esta página constituye la aceptación plena y sin reservas de los nuevos Términos.',
      s8_warning: 'Versión 1.1.0 de Workwii (Blindaje Corporativo).',
      s9_tit: 'Contacto Legal',
      s9_desc: 'Para cualquier consulta legal o técnica, puedes comunicarte directamente con el autor en:',
      s9_c1_title: 'Correo Directo',
      s9_c1_val: 'wilder.taype@hotmail.com',
      s9_c2_title: 'Repositorio Técnico',
      s9_c2_val: 'wtaype/workwii'
    },
    cta: {
      tit: '¿Tienes alguna pregunta?',
      sub: 'Estamos aquí para ayudarte. Contáctanos con total confianza.',
      btnContacto: 'Escribir al equipo',
      btnPrivacidad: 'Ver Privacidad'
    }
  },
  en: {
    seo: {
      titulo: 'Terms and Conditions - Workwii',
      description: 'Rules, responsibilities, intellectual property, and conditions of use under which we offer our free career preparation tools.'
    },
    hero: {
      badge: 'Transparency and Commitment',
      tit1: 'Terms and',
      titGrad: 'Conditions',
      sub: 'By using Workwii, you join a professional community. These terms ensure our space remains <strong>safe, reliable, and protected for everyone.</strong>',
      chip1: 'Your privacy is sacred',
      chip2: 'Free content',
      chip3: 'Fair use',
      lastUpd: 'Last updated: April'
    },
    indices: [
      { id: 'tm_sec_0', ico: 'fa-user-shield', color: '#0EBEFF', txt: 'Platform Use' },
      { id: 'tm_sec_1', ico: 'fa-cloud-bolt', color: '#29C72E', txt: 'Sync & Network' },
      { id: 'tm_sec_2', ico: 'fa-cookie-bite', color: '#FF5C69', txt: 'Ads & Cookies' },
      { id: 'tm_sec_3', ico: 'fa-copyright', color: '#7000FF', txt: 'Intellectual Property' },
      { id: 'tm_sec_4', ico: 'fa-shield-heart', color: '#FFDA34', txt: 'Disclaimer of Liability' },
      { id: 'tm_sec_5', ico: 'fa-ban', color: '#FF5C69', txt: 'Prohibited Content' },
      { id: 'tm_sec_6', ico: 'fa-gavel', color: '#0EBEFF', txt: 'Jurisdiction' },
      { id: 'tm_sec_7', ico: 'fa-rotate', color: '#29C72E', txt: 'Changes' },
      { id: 'tm_sec_8', ico: 'fa-envelope', color: '#7000FF', txt: 'Contact' }
    ],
    sections: {
      badge: 'Content',
      tit: 'Everything you need to ',
      titGrad: 'know',
      sub: 'Read calmly. We are here to be transparent with you.',
      s1_tit: 'Platform Use',
      s1_desc: 'Workwii is a digital platform dedicated to resume optimization and AI interview simulation. It has been built with immense effort, dedication, and personal sacrifice to support the employability of professionals. By accessing, you agree to:',
      s1_item1: 'Respect the work of the creator, the integrity of the software, and the usage rules.',
      s1_item2: 'Do not use AI assistant flows for spam, reverse engineering, or commercial exploitation purposes.',
      s1_item3: 'Maintain a respectful and constructive tone within the platform.',
      s1_item4: 'Be over 13 years old to register an account in the application.',
      s1_item5: 'Accept that this service is offered freely, reserving the right of user admission.',
      s2_tit: 'Synchronization, Network & Devices',
      s2_desc: 'We use advanced local storage (LocalStorage) and database (Supabase) technologies to provide the best real-time experience:',
      s2_item1: 'Your drafts are stored locally in your browser. If you clear history or cache, you will lose them unless you are logged in.',
      s2_item2: 'Proper saving and sync depend directly on your network stability, internet connection, and having a modern and updated browser.',
      s2_item3: 'We are not responsible for data loss caused by network failures, power outages, or obsolete browsers.',
      s2_item4: 'The responsibility to perform backups of your resume content rests solely with you.',
      s3_tit: 'Advertising, Cookies & Chatwii Assistant',
      s3_desc: 'To fund and keep this high-performance ecosystem free, we use cookies and Google AdSense:',
      s3_item1: 'To interact with **Chatwii (our AI Assistant)**, it is mandatory and indispensable to accept and allow the use of cookies and privacy policies.',
      s3_item2: 'If you do not wish to accept or choose to block cookies, chat functionality and AI sync will be disabled to protect data integrity.',
      s3_item3: 'Google AdSense uses cookies (like NID/IDE) to show personalized ads. You can manage them in <a href="https://adssettings.google.com" target="_blank" rel="noopener">Google Ads Settings</a>.',
      s3_item4: 'Bypassing or attempting to bypass cookie blocks to use the AI assistant is strictly prohibited.',
      s4_tit: 'Intellectual Property & Code Shielding',
      s4_desc: 'Workwii is an original project developed by <strong>Wilder Taype</strong>. All rights reserved.',
      s4_item1: 'The source code, visual layout (including the A4 canvas design), CSS styles, animations, AI algorithms, and the Chatwii engine are the exclusive property of its creator.',
      s4_item2: 'Any copy, cloning, distribution, or commercial distribution of interface designs and interactive flows is prohibited without written authorization.',
      s4_item3: 'The written content you enter in your CV (contact, experience, studies) remains your exclusive property. We only give you the canvas to structure it.',
      s4_item4: 'Any suggestion sent via feedback is free for use by the author to optimize the product.',
      s5_tit: 'Limitation and Absolute Exclusion of Liability',
      s5_desc: 'Workwii is provided "AS IS" without warranties of any kind. Since the service is offered for free, our total liability is limited to $0.00 USD:',
      s5_item1: 'We do not guarantee the infallibility or uninterrupted availability of the AI assistant\'s suggestions.',
      s5_item2: 'We are not liable under any circumstances for decisions or results in your application processes, failed interviews, or ATS filter rejections.',
      s5_item3: 'AI hallucinations, writing or grammar errors, or incorrect suggestions must be validated by the user. The user is the final author and editor of their CV.',
      s5_item4: 'We reserve the right to terminate the service, suspend accounts, or modify tools at any time without notice.',
      s6_tit: 'Prohibited Content & Activities',
      s6_desc: 'To maintain a safe ecosystem for all candidates, it is prohibited to:',
      s6_item1: 'Upload fraudulent information, fake degrees, or impersonate identities on the platform.',
      s6_item2: 'Use bots, scrapers, or automated scripts to extract information from the blog or editor.',
      s6_item3: 'Attempt to hack, inject malicious code (SQL or XSS), or sabotage the Supabase database.',
      s6_item4: 'Copy Workwii\'s brand identity or visual material for third-party projects.',
      s6_item5: 'Spam, phish, or defraud using any of the website\'s channels.',
      s7_tit: 'Jurisdiction & Applicable Law',
      s7_desc: 'These Terms are governed by the laws of the Republic of Peru. Any legal dispute or court claim will be resolved exclusively in Lima, Peru.',
      s7_footer: 'If any provision is declared null or unenforceable by a court, it will not affect the validity of the other clauses.',
      s8_tit: 'Changes to Terms',
      s8_desc: 'The creator reserves the right to modify these terms at any time to adapt to new regulations or AI features.',
      s8_footer: 'Continued use of the tools after updating this page constitutes acceptance of the new Terms.',
      s8_warning: 'Version 1.1.0 of Workwii (Corporate Shield).',
      s9_tit: 'Legal Contact',
      s9_desc: 'For legal or technical inquiries, contact the author at:',
      s9_c1_title: 'Direct Email',
      s9_c1_val: 'wilder.taype@hotmail.com',
      s9_c2_title: 'Technical Repository',
      s9_c2_val: 'wtaype/workwii'
    },
    cta: {
      tit: 'Have any questions?',
      sub: 'We are here to help. Contact us with confidence.',
      btnContacto: 'Email the team',
      btnPrivacidad: 'View Privacy'
    }
  }
};
