// src/lib/usuarios/perfil/idiomaPerfil.js
export const idiomaPerfil = {
  es: {
    'perfil.title': 'Mi Perfil',
    'perfil.editar': 'Editar perfil',
    'perfil.nombres': 'Nombres',
    'perfil.tusNombres': 'Tus nombres',
    'perfil.apellidos': 'Apellidos',
    'perfil.tusApellidos': 'Tus apellidos',
    'perfil.avatarUrl': 'Enlace del Avatar (URL)',
    'perfil.avatarPl': 'https://tu-foto.com/imagen.jpg',
    'perfil.nacimiento': 'Fecha de Nacimiento',
    'perfil.genero': 'Género',
    'perfil.selectGenero': 'Selecciona tu género',
    'perfil.masculino': 'Masculino',
    'perfil.femenino': 'Femenino',
    'perfil.otro': 'Otro',
    'perfil.noDecirlo': 'Prefiero no decirlo',
    'perfil.pais': 'País',
    'perfil.ejPais': 'Ej. Perú, México, España...',
    'perfil.gustos': 'Gustos o intereses',
    'perfil.ejGustos': 'Ej. Fútbol, leer, viajar...',
    'perfil.bio': 'Biografía',
    'perfil.tusGustos': 'Cuéntanos un poco sobre ti...',
    'perfil.celular': 'Celular o teléfono',
    'perfil.celularPl': 'Ej. +51 987 654 321',
    'perfil.instagram': 'Usuario de Instagram (@)',
    'perfil.instagramPl': 'Ej. tu_usuario',
    'perfil.tema': 'Tema de la aplicación',
    'perfil.temaCielo': 'Cielo',
    'perfil.temaDulce': 'Dulce',
    'perfil.temaPaz': 'Paz',
    'perfil.temaOro': 'Oro',
    'perfil.temaMora': 'Mora',
    'perfil.temaFuturo': 'Futuro',
    'perfil.guardar': 'Guardar cambios',
    'perfil.guardando': 'Guardando...',
    'perfil.actualizarPass': 'Actualizar contraseña',
    'perfil.nuevaPass': 'Nueva contraseña',
    'perfil.passPl': 'Ingresa tu nueva contraseña',
    'perfil.confPass': 'Confirmar contraseña',
    'perfil.confPassPl': 'Confirma tu nueva contraseña',
    'perfil.datosCuenta': 'Datos de cuenta',
    'perfil.email': 'Email',
    'perfil.plan': 'Plan',
    'perfil.estado': 'Estado',
    'perfil.activo': 'Activo',
    'perfil.registro': 'Registro',
    'perfil.actividad': 'Actividad',
    'perfil.rol': 'Rol',
    'perfil.si': 'Sí',
    'perfil.no': 'No',
    'perfil.recienActivo': 'Recién activo',
    'perfil.desconocido': 'Desconocido',
    'perfil.cargando': 'Cargando...',
    'perfil.contrasenaActualizada': 'Contraseña actualizada correctamente ',
    'perfil.actualizado': 'Perfil actualizado ',
    'perfil.errorGuardar': 'Error al guardar',
    'perfil.errorActualizarPass': 'Error al actualizar contraseña',
    'perfil.minCaracteres': 'Mínimo 6 caracteres',
    'perfil.passNoCoincide': 'Las contraseñas no coinciden',
    'perfil.ingresaNombre': 'Ingresa tu nombre'
  },
  en: {
    'perfil.title': 'My Profile',
    'perfil.editar': 'Edit profile',
    'perfil.nombres': 'First Name',
    'perfil.tusNombres': 'Your first name',
    'perfil.apellidos': 'Last Name',
    'perfil.tusApellidos': 'Your last name',
    'perfil.avatarUrl': 'Avatar Link (URL)',
    'perfil.avatarPl': 'https://your-photo.com/image.jpg',
    'perfil.nacimiento': 'Birth Date',
    'perfil.genero': 'Gender',
    'perfil.selectGenero': 'Select your gender',
    'perfil.masculino': 'Male',
    'perfil.femenino': 'Female',
    'perfil.otro': 'Other',
    'perfil.noDecirlo': 'Prefer not to say',
    'perfil.pais': 'Country',
    'perfil.ejPais': 'E.g. USA, Mexico, Spain...',
    'perfil.gustos': 'Interests / Hobbies',
    'perfil.ejGustos': 'E.g. Soccer, reading, traveling...',
    'perfil.bio': 'Biography',
    'perfil.tusGustos': 'Tell us a bit about yourself...',
    'perfil.celular': 'Cell phone / Phone',
    'perfil.celularPl': 'E.g. +1 555 123 4567',
    'perfil.instagram': 'Instagram Username (@)',
    'perfil.instagramPl': 'E.g. your_username',
    'perfil.tema': 'Application Theme',
    'perfil.temaCielo': 'Cielo',
    'perfil.temaDulce': 'Dulce',
    'perfil.temaPaz': 'Paz',
    'perfil.temaOro': 'Oro',
    'perfil.temaMora': 'Mora',
    'perfil.temaFuturo': 'Futuro',
    'perfil.guardar': 'Save changes',
    'perfil.guardando': 'Saving...',
    'perfil.actualizarPass': 'Update password',
    'perfil.nuevaPass': 'New password',
    'perfil.passPl': 'Enter your new password',
    'perfil.confPass': 'Confirm password',
    'perfil.confPassPl': 'Confirm your new password',
    'perfil.datosCuenta': 'Account info',
    'perfil.email': 'Email',
    'perfil.plan': 'Plan',
    'perfil.estado': 'Status',
    'perfil.activo': 'Active',
    'perfil.registro': 'Registered',
    'perfil.actividad': 'Activity',
    'perfil.rol': 'Role',
    'perfil.si': 'Yes',
    'perfil.no': 'No',
    'perfil.recienActivo': 'Just active',
    'perfil.desconocido': 'Unknown',
    'perfil.cargando': 'Loading...',
    'perfil.contrasenaActualizada': 'Password updated successfully ',
    'perfil.actualizado': 'Profile updated ',
    'perfil.errorGuardar': 'Error saving',
    'perfil.errorActualizarPass': 'Error updating password',
    'perfil.minCaracteres': 'Minimum 6 characters',
    'perfil.passNoCoincide': 'Passwords do not match',
    'perfil.ingresaNombre': 'Enter your name'
  }
};
