export const idiomaPrivacidad = {
  es: {
    seo: {
      titulo: 'Política de Privacidad - Workwii',
      descripcion: 'Conoce cómo protegemos tus datos, CVs y notas en Workwii. Tu privacidad y seguridad son nuestro valor principal.'
    },
    hero: {
      badge: 'Tu privacidad es sagrada',
      tit1: 'Política de',
      titGrad: 'Privacidad',
      sub: 'En Workwii, tu privacidad no es solo una obligación legal — es un <strong>valor fundamental</strong> que guía cada decisión que tomamos.',
      chip1: 'Sin venta de datos',
      chip2: 'Sin rastreo invasivo',
      chip3: '100% seguro',
      lastUpd: 'Última actualización: Abril'
    },
    indices: [
      { id: 'tm_sec_0', ico: 'fa-database', color: '#0EBEFF', txt: 'Información que Recopilamos' },
      { id: 'tm_sec_1', ico: 'fa-gear', color: '#29C72E', txt: 'Cómo Usamos tu Información' },
      { id: 'tm_sec_2', ico: 'fa-bullhorn', color: '#FF5C69', txt: 'Publicidad y Google AdSense' },
      { id: 'tm_sec_3', ico: 'fa-share-nodes', color: '#7000FF', txt: 'Compartir Información con Terceros' },
      { id: 'tm_sec_4', ico: 'fa-cookie-bite', color: '#FFDA34', txt: 'Cookies y Almacenamiento Local' },
      { id: 'tm_sec_5', ico: 'fa-user-lock', color: '#0EBEFF', txt: 'Tus Derechos sobre tus Datos' },
      { id: 'tm_sec_6', ico: 'fa-shield-halved', color: '#29C72E', txt: 'Seguridad de tus Datos' },
      { id: 'tm_sec_7', ico: 'fa-child', color: '#FF5C69', txt: 'Privacidad de Menores' },
      { id: 'tm_sec_8', ico: 'fa-rotate', color: '#7000FF', txt: 'Cambios en esta Política' }
    ],
    sections: {
      badge: 'Privacidad',
      tit: 'Tu información, ',
      titGrad: 'tu control',
      sub: 'Protegemos tus datos para que puedas enfocarte en tu crecimiento profesional.',
      s1_tit: 'Información que Recopilamos',
      s1_desc: 'Workwii recopila únicamente la información necesaria para brindarte las mejores herramientas de optimización profesional y redacción:',
      s1_item1: '<strong>Datos de cuenta:</strong> Nombre, correo electrónico y foto de perfil (si te registras con Google).',
      s1_item2: '<strong>Contenido personal:</strong> Notas de postulación, currículums creados y configuraciones del editor.',
      s1_item3: '<strong>Datos de uso:</strong> Páginas visitadas, tiempo de sesión y funciones utilizadas (de forma anónima).',
      s1_item4: '<strong>Datos técnicos:</strong> Tipo de navegador, sistema operativo y dirección IP (para seguridad y diagnóstico).',
      s1_warning: 'Jamás recopilamos información financiera, contraseñas ni datos sensibles fuera de lo necesario para el inicio de sesión con Google.',
      s2_tit: 'Cómo Usamos tu Información',
      s2_desc: 'La información que recopilamos tiene un único propósito: mejorar tu experiencia de redacción y preparación en Workwii.',
      s2_item1: 'Personalizar tu experiencia y recordar tus preferencias de tema visual y edición.',
      s2_item2: 'Sincronizar tus datos entre dispositivos de forma segura.',
      s2_item3: 'Mejorar la plataforma identificando errores y áreas de mejora.',
      s2_item4: 'Enviarte notificaciones importantes sobre cambios en el servicio (solo si te registraste).',
      s2_item5: 'Mostrar publicidad relevante a través de Google AdSense para mantener el servicio gratuito.',
      s3_tit: 'Publicidad y Google AdSense',
      s3_desc: 'Workwii utiliza <strong>Google AdSense</strong> para mostrar anuncios publicitarios. Este servicio:',
      s3_item1: 'Puede usar cookies para mostrar anuncios basados en tus visitas previas a Workwii y otros sitios web.',
      s3_item2: 'Google, como proveedor externo, utiliza cookies para servir anuncios según el historial de visitas del usuario.',
      s3_item3: 'Puedes optar por no recibir anuncios personalizados visitando <a href="https://adssettings.google.com" target="_blank" rel="noopener">Google Ads Settings</a>.',
      s3_item4: 'También puedes desactivar el uso de cookies de terceros en la configuración de tu navegador.',
      s3_warning: 'Para más información sobre cómo Google usa los datos cuando utilizas sitios con AdSense, visita <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener">policies.google.com</a>.',
      s4_tit: 'Compartir Información con Terceros',
      s4_desc: 'Workwii no vende, alquila ni comercializa tu información personal. Únicamente compartimos datos en estos casos:',
      s4_item1: '<strong>Supabase:</strong> Para autenticación, base de datos y almacenamiento en la nube.',
      s4_item2: '<strong>Google AdSense:</strong> Para mostrar anuncios publicitarios relevantes.',
      s4_item3: '<strong>Requerimiento legal:</strong> Si la ley lo exige o para proteger los derechos de Workwii y sus usuarios.',
      s4_footer: 'Todos nuestros proveedores de terceros cumplen con los más altos estándares internacionales de seguridad y privacidad.',
      s5_tit: 'Cookies y Almacenamiento Local',
      s5_desc: 'Utilizamos cookies y LocalStorage para mejorar tu experiencia. Para interactuar con nuestro Asistente IA Chatwii, la aceptación de estas políticas es estrictamente obligatoria. Para más detalles, consulta nuestra <a href="/cookies" class="tm_nav">Política de Cookies</a>.',
      s5_item1: '<strong>Cookies esenciales:</strong> Necesarias para que la app funcione correctamente.',
      s5_item2: '<strong>LocalStorage:</strong> Guarda tus preferencias de tema y datos offline para carga instantánea.',
      s5_item3: '<strong>Cookies de publicidad:</strong> Usadas por Google AdSense para anuncios relevantes.',
      s6_tit: 'Tus Derechos sobre tus Datos',
      s6_desc: 'En Workwii, tú tienes el control total sobre tu información personal:',
      s6_item1: '<strong>Acceso:</strong> Puedes solicitar una copia de tus datos personales en cualquier momento.',
      s6_item2: '<strong>Rectificación:</strong> Puedes corregir información incorrecta desde tu perfil.',
      s6_item3: '<strong>Eliminación:</strong> Puedes solicitar la eliminación de tu cuenta y todos tus datos.',
      s6_item4: '<strong>Portabilidad:</strong> Puedes exportar tus notas y datos en cualquier momento.',
      s6_item5: '<strong>Oposición:</strong> Puedes oponerte al uso de tus datos para publicidad personalizada.',
      s6_warning: 'Para ejercer cualquiera de estos derechos, contáctanos a <a href="mailto:wilder.taype@hotmail.com">wilder.taype@hotmail.com</a>. Responderemos en un plazo máximo de 30 días.',
      s7_tit: 'Seguridad de tus Datos',
      s7_desc: 'Implementamos múltiples capas de seguridad física y digital para proteger tu información, sin embargo, ningún sistema de transmisión de datos en internet es 100% inexpugnable:',
      s7_item1: 'Toda la comunicación entre tu dispositivo y nuestros servidores está cifrada con HTTPS/TLS.',
      s7_item2: 'Utilizamos Supabase, que cumple con estándares de seguridad ISO 27001, SOC 2 y cifrado en reposo/tránsito.',
      s7_item3: 'Las contraseñas nunca se almacenan en texto plano; usamos autenticación OAuth de Google.',
      s7_item4: 'El usuario asume la responsabilidad de proteger el acceso a sus propios dispositivos y navegadores.',
      s8_tit: 'Privacidad de Menores',
      s8_desc: 'Workwii está diseñado para personas de todas las edades, pero con responsabilidad:',
      s8_item1: 'No recopilamos conscientemente datos personales de menores de 13 años sin consentimiento parental.',
      s8_item2: 'Si eres padre/tutor y crees que tu hijo nos proporcionó datos, contáctanos para eliminarlos.',
      s8_item3: 'Recomendamos supervisión parental para el uso de todas las funciones interactivas.',
      s9_tit: 'Cambios en esta Política',
      s9_desc: 'Nos reservamos el derecho de actualizar esta Política de Privacidad cuando sea necesario. Te notificaremos sobre cambios significativos a través de la plataforma.',
      s9_warning: 'Última actualización: Abril · Al continuar usando Workwii después de los cambios, aceptas la política actualizada.'
    },
    cta: {
      tit: '¿Tienes dudas sobre<br>tu privacidad?',
      sub: 'Escríbenos y te responderemos en menos de 48 horas.',
      btnContacto: 'Contactar al equipo',
      btnTerminos: 'Ver Términos'
    }
  },
  en: {
    seo: {
      titulo: 'Privacy Policy - Workwii',
      descripcion: 'Learn how we protect your data, CVs, and notes on Workwii. Your privacy and security are our core values.'
    },
    hero: {
      badge: 'Your privacy is sacred',
      tit1: 'Privacy',
      titGrad: 'Policy',
      sub: 'At Workwii, your privacy is not just a legal obligation — it is a <strong>fundamental value</strong> that guides every decision we make.',
      chip1: 'No selling data',
      chip2: 'No invasive tracking',
      chip3: '100% secure',
      lastUpd: 'Last updated: April'
    },
    indices: [
      { id: 'tm_sec_0', ico: 'fa-database', color: '#0EBEFF', txt: 'Information We Collect' },
      { id: 'tm_sec_1', ico: 'fa-gear', color: '#29C72E', txt: 'How We Use Your Info' },
      { id: 'tm_sec_2', ico: 'fa-bullhorn', color: '#FF5C69', txt: 'Advertising & AdSense' },
      { id: 'tm_sec_3', ico: 'fa-share-nodes', color: '#7000FF', txt: 'Sharing Data with Third Parties' },
      { id: 'tm_sec_4', ico: 'fa-cookie-bite', color: '#FFDA34', txt: 'Cookies & Local Storage' },
      { id: 'tm_sec_5', ico: 'fa-user-lock', color: '#0EBEFF', txt: 'Your Rights Over Your Data' },
      { id: 'tm_sec_6', ico: 'fa-shield-halved', color: '#29C72E', txt: 'Data Security' },
      { id: 'tm_sec_7', ico: 'fa-child', color: '#FF5C69', txt: 'Children\'s Privacy' },
      { id: 'tm_sec_8', ico: 'fa-rotate', color: '#7000FF', txt: 'Changes to this Policy' }
    ],
    sections: {
      badge: 'Privacy',
      tit: 'Your data, ',
      titGrad: 'your control',
      sub: 'We protect your data so you can focus on your professional growth.',
      s1_tit: 'Information We Collect',
      s1_desc: 'Workwii collects only the information necessary to provide you with the best professional optimization and writing tools:',
      s1_item1: '<strong>Account data:</strong> Name, email address, and profile picture (if you register with Google).',
      s1_item2: '<strong>Personal content:</strong> Application notes, created resumes, and editor configurations.',
      s1_item3: '<strong>Usage data:</strong> Visited pages, session duration, and used functions (anonymously).',
      s1_item4: '<strong>Technical data:</strong> Browser type, operating system, and IP address (for security and diagnostics).',
      s1_warning: 'We never collect financial information, passwords, or sensitive data outside of what is necessary for Google sign-in.',
      s2_tit: 'How We Use Your Information',
      s2_desc: 'The information we collect has a single purpose: to improve your writing and preparation experience on Workwii.',
      s2_item1: 'Personalize your experience and remember your visual theme and editing preferences.',
      s2_item2: 'Synchronize your data securely between devices.',
      s2_item3: 'Improve the platform by identifying bugs and areas for enhancement.',
      s2_item4: 'Send you important notifications about service changes (only if you registered).',
      s2_item5: 'Display relevant advertising through Google AdSense to keep the service free.',
      s3_tit: 'Advertising and Google AdSense',
      s3_desc: 'Workwii uses <strong>Google AdSense</strong> to show advertisements. This service:',
      s3_item1: 'May use cookies to show ads based on your previous visits to Workwii and other websites.',
      s3_item2: 'Google, as a third-party provider, uses cookies to serve ads based on user visit history.',
      s3_item3: 'You can choose to opt out of personalized ads by visiting <a href="https://adssettings.google.com" target="_blank" rel="noopener">Google Ads Settings</a>.',
      s3_item4: 'You can also disable third-party cookies in your browser settings.',
      s3_warning: 'For more information on how Google uses data when you use sites with AdSense, visit <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener">policies.google.com</a>.',
      s4_tit: 'Sharing Information with Third Parties',
      s4_desc: 'Workwii does not sell, rent, or trade your personal information. We only share data in these cases:',
      s4_item1: '<strong>Supabase:</strong> For authentication, database, and cloud storage.',
      s4_item2: '<strong>Google AdSense:</strong> To show relevant advertisements.',
      s4_item3: '<strong>Legal requirement:</strong> If required by law or to protect the rights of Workwii and its users.',
      s4_footer: 'All our third-party providers comply with the highest international security and privacy standards.',
      s5_tit: 'Cookies and Local Storage',
      s5_desc: 'We use cookies and LocalStorage to improve your experience. To interact with our Chatwii AI Assistant, acceptance of these policies is strictly mandatory. For details, see our <a href="/en/cookies" class="tm_nav">Cookies Policy</a>.',
      s5_item1: '<strong>Essential cookies:</strong> Needed for the app to function correctly.',
      s5_item2: '<strong>LocalStorage:</strong> Saves your theme preferences and offline data for instant load.',
      s5_item3: '<strong>Advertising cookies:</strong> Used by Google AdSense for relevant ads.',
      s6_tit: 'Your Rights Over Your Data',
      s6_desc: 'At Workwii, you have total control over your personal information:',
      s6_item1: '<strong>Access:</strong> You can request a copy of your personal data at any time.',
      s6_item2: '<strong>Correction:</strong> You can correct incorrect information from your profile.',
      s6_item3: '<strong>Deletion:</strong> You can request deletion of your account and all your data.',
      s6_item4: '<strong>Portability:</strong> You can export your notes and resume data at any time.',
      s6_item5: '<strong>Object:</strong> You can object to the use of your data for personalized advertising.',
      s6_warning: 'To exercise any of these rights, contact us at <a href="mailto:wilder.taype@hotmail.com">wilder.taype@hotmail.com</a>. We will respond within a maximum of 30 days.',
      s7_tit: 'Security of Your Data',
      s7_desc: 'We implement multiple physical and digital security layers to protect your data; however, no internet data transmission system is 100% secure:',
      s7_item1: 'All communication between your device and our servers is encrypted with HTTPS/TLS.',
      s7_item2: 'We use Supabase, which complies with ISO 27001, SOC 2 security standards, and encryption at rest/in transit.',
      s7_item3: 'Passwords are never stored in plain text; we use Google OAuth authentication.',
      s7_item4: 'The user assumes the responsibility to protect access to their own devices and browsers.',
      s8_tit: 'Children\'s Privacy',
      s8_desc: 'Workwii is designed for people of all ages, but with responsibility:',
      s8_item1: 'We do not knowingly collect personal data from children under 13 without parental consent.',
      s8_item2: 'If you are a parent/guardian and believe your child provided data, contact us to delete it.',
      s8_item3: 'We recommend parental supervision for using all interactive features.',
      s9_tit: 'Changes to this Policy',
      s9_desc: 'We reserve the right to update this Privacy Policy when necessary. We will notify you of significant changes through the platform.',
      s9_warning: 'Last updated: April · By continuing to use Workwii after changes, you accept the updated policy.'
    },
    cta: {
      tit: 'Have questions about<br>your privacy?',
      sub: 'Write to us and we will respond in less than 48 hours.',
      btnContacto: 'Contact team',
      btnTerminos: 'View Terms'
    }
  }
};
